// products.js
export const products = [
    {
      id: 1,
      name: "Fresh Orange Juice",
      price: 30,
      description: "A refreshing glass of fresh orange juice, full of vitamin C.",
      image: "https://images.pexels.com/photos/5938417/pexels-photo-5938417.jpeg",
      category: "Beverages",
    },
    {
      id: 2,
      name: "Classic Cheeseburger",
      price: 50,
      description: "A delicious cheeseburger with fresh lettuce, tomato, and cheddar cheese.",
      image: "https://images.pexels.com/photos/1639566/pexels-photo-1639566.jpeg",
      category: "Food",
    },
    {
      id: 3,
      name: "French Fries",
      price: 25,
      description: "Crispy golden french fries, a perfect side for any meal.",
      image: "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg",
      category: "Snacks",
    },
    {
        id: 4,
        name: "Chocolate Milkshake",
        price: 35,
        description: "A rich and creamy chocolate milkshake topped with whipped cream.",
        image: "https://images.pexels.com/photos/3756621/pexels-photo-3756621.jpeg",
        category: "Beverages",
      },
    {
      id: 5,
      name: "Caesar Salad",
      price: 40,
      description: "A fresh Caesar salad with crunchy croutons and parmesan cheese.",
      image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
      category: "Food",
    },
    {
      id: 6,
      name: "Spaghetti Carbonara",
      price: 70,
      description: "Creamy spaghetti carbonara with crispy bacon and fresh herbs.",
      image: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg",
      category: "Food",
    },
    {
        id: 7,
        name: "Ice Cream Sundae",
        price: 20,
        description: "A delicious ice cream sundae with chocolate syrup and a cherry on top.",
        image: "https://images.pexels.com/photos/461206/pexels-photo-461206.jpeg",
        category: "Desserts",
      },
    {
      id: 8,
      name: "Grilled Chicken Sandwich",
      price: 55,
      description: "A healthy grilled chicken sandwich with fresh vegetables and mayo.",
      image: "https://images.pexels.com/photos/1565982/pexels-photo-1565982.jpeg",
      category: "Food",
    },
    {
      id: 9,
      name: "Iced Coffee",
      price: 28,
      description: "Cold, refreshing iced coffee to boost your energy.",
      image: "https://images.pexels.com/photos/374885/pexels-photo-374885.jpeg",
      category: "Beverages",
    },
    {
      id: 10,
      name: "Chocolate Chip Cookies",
      price: 15,
      description: "Soft and chewy chocolate chip cookies, perfect for a quick snack.",
      image: "https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg",
      category: "Desserts",
    },
  ];
  